# Основная конфигурация
root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  # Команда сборки (обычно бинарник кладется в папку tmp)
  cmd = "go build -o ./tmp/main ./cmd/telegram/main.go"
  
  # Команда запуска полученного бинарника
  bin = "./tmp/main"
  
  # Дополнительные аргументы при запуске приложения (например, флаги)
  args_bin = []
  
  # Наблюдать за этими расширениями
  include_ext = ["go", "tpl", "tmpl", "html", "yaml", "yml", "toml", "env"]
  
  # Игнорировать эти директории
  exclude_dir = ["assets", "tmp", "vendor", "testdata", ".git"]
  
  # Игнорировать конкретные файлы
  exclude_file = []
  
  # Игнорировать изменения в файлах по паттерну (например, _test.go)
  exclude_regex = ["_test.go"]
  
  # Задержка перед сборкой после изменения (чтобы не спамить рестартами при быстром сохранении)
  delay = 1000 # в миллисекундах
  
  # Останавливать старый бинарник, если сборка новой версии упала
  stop_on_error = true
  
  # Цвет логов
  log_color = true

[log]
  time = true

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  # Удалять папку tmp при выходе из Air
  clean_on_exit = true